id: P007101
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24018
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ།
  author: ''
  volumes:
    3c9cb1a25f48431cabd85c7404882437:
      image_group_id: I1KG24077
      title: ''
      volume_number: 1
      total_pages: 314
ebook_metadata:
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ།
  author: ''
  sku: P007101
  cover: cover.jpg
  layers:
  - pagination
