id: P007101
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:42.004403
source_metadata:
  id: bdr:W1KG24018
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ།
  author: ''
  volumes:
    db0c840c28a54b95b7df192182c2cfb3:
      image_group_id: I1KG24077
      title: Volume 1 of dga' ldan shar rtse'i chos spyod mdzad rim/
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
