id: I98FF0B01
legacy_id: P007101
ocr_import_info:
  bdrc_scan_id: W1KG24018
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T10:55:59'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:32:03.430696+00:00'
last_modified: 2022-08-27 15:32:37.406597
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG24018
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG24018
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ།
  author: སྤྲུལ་སྐུ་འཕགས་པ་བློ་གསལ།
statistics:
  ocr_word_mean_confidence_index: 0.8377213065515399
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I1KG24077:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24077
      total_pages: 314
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24077.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8377213065515399
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
